### ISSUE TITLE
wrong reference to account_bank_statement_import in the README

### ISSUE THREAD

**Issue by rvalyi** [OCA/bank-statement-import#114]
Hello, the repo README states:
```
This repository hosts:

-  a 10.0 backport of the account_bank_statement_import modules from the master branch
```

But this was true until the 8.0 branch. In the 9.0 and 10.0 branches this is not true anymore as the account_bank_statement_import is now part of the Odoo SA core modules. So I think we should remove this statements from the README in the 9.0 and 10.0 branches to clarify.

**Comment by pedrobaeza** [comment]
Right, please make a PR removing that line on v9/v10.
