### ISSUE TITLE
[IMPROVEMENT] SNS Bank MT940 Support

### ISSUE THREAD

**Issue by melroy89** [OCA/bank-statement-import#140]
Hi,

SNS Bank also allows you to download MT940 file format (both personal & business account).

We can create a new module, called: `account_bank_statement_import_mt940_nl_sns`.

I attached example from a MT940 export file (by default zipped in a zip file). And a specification file of SNS itself.
See both attachments below.

**SNS Informatiewijzer**
[6_0016_35_1511_Informatiewijzer_MT940_rapportage.pdf](https://github.com/OCA/bank-statement-import/files/1603365/6_0016_35_1511_Informatiewijzer_MT940_rapportage.pdf)

**MT940 Export file example**
[tr-info_15785279_20180104123832.zip](https://github.com/OCA/bank-statement-import/files/1603378/tr-info_15785279_20180104123832.zip)

I hope we can make a new SNS module to support importing MT940 files to Odoo!

Regards,
Melroy van den Berg

**Comment by feketemihai** [comment]
@danger89 support for sns is added in v10 and v11. @pedrobaeza can you please close this one.
