### ISSUE TITLE
import qif for odoo 11?

### ISSUE THREAD

**Issue by metrogeekythinker** [OCA/bank-statement-import#164]
I managed to install successfully but am getting this error when uploading.

"Could not make sense of the given file.
Did you install the module to support this type of file ?"

Console error as follow:
web.assets_common.js:3832 Server application error {"message":"Odoo Server Error","data":{"name":"odoo.exceptions.UserError","message":"Could not make sense of the given file.\nDid you install the module to support this type of file ?\n","exception_type":"user_error","arguments":["Could not make sense of the given file.\nDid you install the module to support this type of file ?",""],"debug":"Traceback (most recent call last):\n  File \"/opt/odoo/odoo/odoo/http.py\", line 650, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/opt/odoo/odoo/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/opt/odoo/odoo/odoo/http.py\", line 692, in dispatch\n    result = self._call_function(**self.params)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/opt/odoo/odoo/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 936, in __call__\n    return self.method(*args, **kw)\n  File \"/opt/odoo/odoo/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/opt/odoo/odoo/addons/web/controllers/main.py\", line 935, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/opt/odoo/odoo/addons/web/controllers/main.py\", line 923, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/opt/odoo/odoo/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/opt/odoo/odoo/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/opt/odoo/odoo/addons/muk_account_bank_statement_import_sheet/wizards/account_bank_statement_import.py\", line 72, in import_file\n    return super(AccountBankStatementImport, self).import_file()\n  File \"/opt/odoo/odoo/addons/account_bank_statement_import/account_bank_statement_import.py\", line 37, in import_file\n    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))\n  File \"/opt/odoo/odoo/addons/account_bank_statement_import_qif/wizards/account_bank_statement_import_qif.py\", line 24, in _parse_file\n    data_file)\n  File \"/opt/odoo/odoo/addons/account_bank_statement_import/account_bank_statement_import.py\", line 108, in _parse_file\n    raise UserError(_('Could not make sense of the given file.\\nDid you install the module to support this type of file ?'))\nodoo.exceptions.UserError: ('Could not make sense of the given file.\\nDid you install the module to support this type of file ?', '')\n"},"code":200}

**Comment by pedrobaeza** [comment]
Try on runbot: https://runbot.odoo-community.org

**Comment by metrogeekythinker** [comment]
Tried and tested. Same error.
Console as follow:
web.assets_common.js:3833 Server application error {"code":200,"data":{"name":"odoo.exceptions.UserError","arguments":["Could not make sense of the given file.\nDid you install the module to support this type of file ?",""],"message":"Could not make sense of the given file.\nDid you install the module to support this type of file ?\n","exception_type":"user_error","debug":"Traceback (most recent call last):\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 650, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/home/odoo/build/OCA/OCB/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 692, in dispatch\n    result = self._call_function(**self.params)\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/home/odoo/build/OCA/OCB/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 936, in __call__\n    return self.method(*args, **kw)\n  File \"/home/odoo/build/OCA/OCB/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/home/odoo/OCB-11.0/addons/web/controllers/main.py\", line 935, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/home/odoo/OCB-11.0/addons/web/controllers/main.py\", line 923, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/home/odoo/build/OCA/OCB/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/home/odoo/build/OCA/OCB/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/home/odoo/OCB-11.0/addons/account_bank_statement_import/account_bank_statement_import.py\", line 37, in import_file\n    currency_code, account_number, stmts_vals = self.with_context(active_id=self.ids[0])._parse_file(base64.b64decode(self.data_file))\n  File \"/home/odoo/OCB-11.0/addons/account_bank_statement_import/account_bank_statement_import.py\", line 112, in _parse_file\n    raise UserError(_('Could not make sense of the given file.\\nDid you install the module to support this type of file ?'))\nodoo.exceptions.UserError: ('Could not make sense of the given file.\\nDid you install the module to support this type of file ?', '')\n"},"message":"Odoo Server Error"}
(anonymous) @ web.assets_common.js:3833

**Comment by pedrobaeza** [comment]
I'm afraid without the QIF file, it's not possible to debug, but for sure it contains confidential information and this seems out of scope of the issue tracker. If you have a trace about the exact problem, then maybe this can be reconsidered, but without more information, it's not possible.

**Comment by metrogeekythinker** [comment]
So no one have even tested this? Although this could be out of scope, but dont you think it is too quick to close the issue as there might be others who might have a clue? I just want to know whether anyone successfully import a QIF file.

**Comment by pedrobaeza** [comment]
No, there's no possible clue. That's the standard message saying that the file is not recognized, and yes, it's tested and working on my side with some QIF files.
