### ISSUE TITLE
Will Camt be supported?

### ISSUE THREAD

**Issue by mivaho** [OCA/bank-statement-import#17]
Hi,
I'm trying to import bank statements from the dutch bank Triodos but I'm not having success at the moment.

I tried the import camt module by NL66278 but it either doesn't import all the statements (from a an xml with 2 months worth of statements) or when I do them 1 by 1 it takes the first file but with the second it says it was already imported. Can't raise an issue at NL66278's github page.

So I was wondering if it will get merged into this import module or if someone has another way of getting Triodos statements in to Odoo.

**Comment by yvaucher** [comment]
@mivaho use `@` if you want to address to someone

ping @NL66278
