### ISSUE TITLE
CAMT parser: Remittance information hidden in note field

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-statement-import#176]
Hi,

This is a question of CAMT users.

In this code:

https://github.com/OCA/bank-statement-import/blob/6fc3202c311761ebc78e98013c11b9cf2b4f5bb2/account_bank_statement_import_camt_oca/models/parser.py#L56-L67

we see that the Remittance information is put in the note field, while the Additional Tx Information is put in the name field.

In reconciliation and visualisation of the bank statement in Odoo, the note field is visible only by hovering over the i icon. However the most relevant information for the user is the remittance information (which incidentally is also the communication field as used by OCA/bank-payment).

What do people think about this?

**Comment by astirpe** [comment]
We have the same issue. In all our customers we installed a patched module, in which `note` and `name` are switched. I'm going to open a PR with the patch soon.

**Comment by astirpe** [comment]
I created 3 PRs for 9.0, 10.0 and 11.0.

@yung-wang I know you are interested in this!
