### ISSUE TITLE
Active PRs status

### ISSUE THREAD

**Issue by lmignon** [OCA/bank-statement-import#18]
A try to summarize the current situation...
- #14 Add the possibility to bulk import files containing bank statements. This PR requires a change to the API. Following a discussion with @qdp-odoo, a PR on upstream has been done including the required changes and the migration to the new API odoo/odoo#5863. The PR on upstream is under review. We have been trying to contact @qdp-odoo to see if the branch can be merged in odoo master, but no luck so far.
-  https://github.com/acsone/bank-statement-import/tree/8.0-refactor-new-api is the backport of  odoo/odoo#5863 (WIP)
- #13 fix identify partner by res.partner.bank. This PR will not be necessary if the backport is merged since a more generic fix has been provided (see comments https://github.com/OCA/bank-statement-import/pull/13#issuecomment-84653446, ...)
- #4 Add camt and mt940 import, including the changes to support multiple accounts and currencies per file.  ??? superseded by #15 ???
- #15 same as #4 but based on the work done in https://github.com/acsone/bank-statement-import/tree/8.0-refactor-new-api .

**Comment by sbidoul** [comment]
Ok, things gets a bit clearer thanks to @qdp-odoo's comments on https://github.com/odoo/odoo/pull/5863. I think we have now reached a stage where maintaining a pure backport of master in 8.0 is not feasible anymore so it will be more efficient to maintain a separate version of the import framework for 8.0.

So I suggest @lmignon does a PR with https://github.com/acsone/bank-statement-import/tree/8.0-refactor-new-api and we review that as well as @NL66278 's additions. 

All while keeping an eye on how master evolves to make sure the parsers remain as much as possible forward compatible with master.

**Comment by lmignon** [comment]
@sbidoul PR done https://github.com/OCA/bank-statement-import/pull/19
