### ISSUE TITLE
A bank account transactions can be imported only once

### ISSUE THREAD

**Issue by enriquevago** [OCA/bank-statement-import#195]
### I reinstalled odoo several times in I have this error, ever time the first import I got this message...

Server application error {"code":200,"message":"Odoo Server Error","data":{"name":"odoo.exceptions.ValidationError","debug":"Traceback (most recent call last):\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/service/model.py\", line 97, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 335, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 937, in __call__\n    return self.method(*args, **kw)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 515, in response_wrap\n    response = f(*args, **kw)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/web/controllers/main.py\", line 938, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/web/controllers/main.py\", line 926, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/account_bank_statement_import/account_bank_statement_import.py\", line 51, in import_file\n    statement_ids, notifications = self._create_bank_statements(stmts_vals)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/account_bank_statement_import/account_bank_statement_import.py\", line 238, in _create_bank_statements\n    statement_ids.append(BankStatement.create(st_vals).id)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/mail/models/mail_thread.py\", line 238, in create\n    thread = super(MailThread, self).create(values)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/models.py\", line 3373, in create\n    record = self.browse(self._create(old_vals))\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/models.py\", line 3520, in _create\n    field.write(self.with_context(rel_context), vals[name], create=True)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/fields.py\", line 2275, in write\n    comodel.create(act[2])\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/addons/account/models/account_bank_statement.py\", line 393, in create\n    line = super(AccountBankStatementLine, self).create(vals)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/models.py\", line 3373, in create\n    record = self.browse(self._create(old_vals))\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/models.py\", line 3466, in _create\n    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/sql_db.py\", line 155, in wrapper\n    return f(self, *args, **kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/sql_db.py\", line 232, in execute\n    res = self._obj.execute(query, params)\npsycopg2.IntegrityError: duplicate key value violates unique constraint \"account_bank_statement_line_unique_import_id\"\nDETAIL:  Key (unique_import_id)=(56D4B152A58E40E9B9EF6B6976F56C50-7-26/12/2017077) already exists.\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 651, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 310, in _handle_exception\n    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/tools/pycompat.py\", line 87, in reraise\n    raise value\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 693, in dispatch\n    result = self._call_function(**self.params)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/http.py\", line 342, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/opt/odoo-server/apps/odoo/lib/odoo-11.0.post20181218-py3.7.egg/odoo/service/model.py\", line 119, in wrapper\n    raise ValidationError(tr(registry._sql_error[key], 'sql_constraint') or inst.pgerror)\nodoo.exceptions.ValidationError: ('A bank account transactions can be imported only once !', None)\n","message":"A bank account transactions can be imported only once !\nNone","arguments":["A bank account transactions can be imported only once !",null],"exception_type":"validation_error"}}

**Comment by pedrobaeza** [comment]
The message is clear: you're trying to import an already imported transaction.

**Comment by enriquevago** [comment]
I not,this first this occurs on the first import and already it shows this message ! i try to make and  several different ways this occurs !

**Comment by pedrobaeza** [comment]
Then on the same file there should be 2 transactions with the same identifier. You should check in the format you are importing (that you haven't even reported), which is the identifier that is taken for the statement line.

**Comment by matanaurus** [comment]
I am having a similar issue. Both the bank statement date, identifier and values are unique and I have never imported to this bank, and yet I still get a "A bank account transactions can be imported only once". I don't know how I am supposed to traceback to see where exactly everything fails.
