### ISSUE TITLE
import ofx should not have auto_install set to True

### ISSUE THREAD

**Issue by nbessi** [OCA/bank-statement-import#22]
I do not think  we should automatically install this module by defaut when we install bank statement import addons.

It has an external Python dependency that may prevent other localisation parser to be installed simply because the installation of the ofx parser failed.

**Comment by lmignon** [comment]
:+1: a legacy of the past

**Comment by pedrobaeza** [comment]
Yeah :+1:

**Comment by nbessi** [comment]
ok I'll do a PR

**Comment by nbessi** [comment]
see #23
