### ISSUE TITLE
OFX statement import with non IBAN account

### ISSUE THREAD

**Issue by pascalthivierge** [OCA/bank-statement-import#232]
When I try to import an OFX statement to a non-IBAN account in v.12, I get the following error:

> The IBAN is invalid, it should begin with the country code

How do I import my statements ?

Thanks in advance!

**Comment by sciallo** [comment]
Same problem here did you ever figure it out?

**Comment by sciallo** [comment]
In my case the account number I set up my bank with in ODOO was different than what the bank OFX file had in it. (they had 'CKBCF-xxxxxx' where xxxxx is the acct number in the ACCTID tag) all I had to do  is change the bank account number in odoo to match what's in the \<ACCTID\> tag and it works fine now.

I hope this helps someone.

**Comment by vanderleiromera** [comment]
> In my case the account number I set up my bank with in ODOO was different than what the bank OFX file had in it. (they had 'CKBCF-xxxxxx' where xxxxx is the acct number in the ACCTID tag) all I had to do is change the bank account number in odoo to match what's in the <ACCTID> tag and it works fine now.
> 
> I hope this helps someone.

Thank you, change the ACCTID in odoo solved!

**Comment by marcelsavegnago** [comment]
https://github.com/OCA/bank-statement-import/pull/539
