### ISSUE TITLE
[RFC] account_bank_statement_import_paypal

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/bank-statement-import#235]
@pedrobaeza Tecnativa worked on this module, and I'm thinking that it could use some improvement, but it seems that it will be _significant_. Whom to talk with about that? I want to:
 - Enhance fields mapping
 - Stop merging currency exchange lines (that is just not correct for accounting!)
 - Import only matching currency
 - Issue unique ID for commission lines as well
 - Support both statements and activity reports import

BUT! So far it looks like a complete module revamp would be faster and easier for me. And I want to talk to someone about that

**Comment by pedrobaeza** [comment]
OK, I'm the man. While we provide migration scripts for existing installed base, it should be good, but I will review the code when the PR is out.

**Comment by alexey-pelykh** [comment]
@pedrobaeza if possible, can you provide a sample from Spanish PayPal reports: Activity and Statement (different headers)? And if you have other locales as well

**Comment by alexey-pelykh** [comment]
https://github.com/OCA/bank-statement-import/pull/236 this one has no migrations yet, it would be good to check the overall behaviour and agree on that first

**Comment by pedrobaeza** [comment]
OK, I will see if I can have a sample.
