### ISSUE TITLE
[RFC] account_bank_statement_import_advanced

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/bank-statement-import#237]
@pedrobaeza I want to create another module that would allow importing one large statement splitting it by days, weeks, or months. And few other improvements like partner resolution using extra fields (move that out of paypal). But I don't want to rush with naming of module before you say ok to avoid changing the name afterwards.

**Comment by pedrobaeza** [comment]
Do they need any common base? I don't think so. Thus, put each feature in a module and name them accordingly:

- About the splitting: `account_bank_statement_import_split`
- About partner resolution: `account_bank_statement_import_partner_matching`.

**Comment by alexey-pelykh** [comment]
👍 thank you, master of naming ) one of reasons - I had no good name for modules

**Comment by pedrobaeza** [comment]
![imagen](https://user-images.githubusercontent.com/7165771/68660815-2d089280-053a-11ea-9300-6a8e9b3bc49d.png)
