### ISSUE TITLE
[RFC] statement line date vs datetime

### ISSUE THREAD

**Issue by alexey-pelykh** [OCA/bank-statement-import#238]
@pedrobaeza I've seen this voodoo magic in other module you've created, so maybe there's a value of changing statement line date field to datetime?

**Comment by pedrobaeza** [comment]
I don't get what you mean

**Comment by alexey-pelykh** [comment]
https://github.com/odoo/odoo/blob/b3d4c2d178bb3dbb9875271082bc36a80076e649/addons/account/models/account_bank_statement.py#L289

many statements have more precision on timing of transaction than just a date

**Comment by alexey-pelykh** [comment]
So maybe add module that enhances this field to Datetime?

**Comment by pedrobaeza** [comment]
But in practical terms, why do you need that? At accounting level, date is enough. Any way, you can do something similar to https://github.com/OCA/project/blob/12.0/project_timesheet_time_control/models/account_analytic_line.py, that adds the datetime field and automatically reflects it to the date field for compatibility.

**Comment by alexey-pelykh** [comment]
Date doesn't have timezone, and at edge cases that starts to be a problem of "this transaction was in other week"

**Comment by pedrobaeza** [comment]
But that should be handled on import, not on data model.

**Comment by alexey-pelykh** [comment]
100%, importers would need to support passing full datetime when available

**Comment by pedrobaeza** [comment]
Not exactly, my point is that if importer needs to be tz aware, it should include that configuration and parse data and convert to proper date according it, but finally passing only a date.

**Comment by alexey-pelykh** [comment]
but again, importer will provide date in what timezone? UTC? seems so, and then this date would be shown to user that is not in UTC. Maybe I'm mixing something up, yet that's how I got it

**Comment by pedrobaeza** [comment]
What you are suggesting will mean that depending on the user that sees the bank statement, he/she can see a different day depending on their timezone. That's simply not correct.

When you download a bank statement, that bank statement can contain datetime with certain timezone. If that's the case, you have to convert to UTC that information on import, and extract the date from it. But nothing more.

**Comment by alexey-pelykh** [comment]
Makes perfect sense to me
