### ISSUE TITLE
[8.0] Constraint unique over 'sanitazed_acc_number'

### ISSUE THREAD

**Issue by antespi** [OCA/bank-statement-import#24]
We've just update a customer with last changes, including PR : https://github.com/OCA/bank-statement-import/pull/19
And we've have this issue.

Our customer has two partners with the same acc_number. I understand that this use case is not common (or maybe a mistake by user) in B2B. But in B2C it could happend. For example, my wife and me have the same acc_number (we are co-titulars), and want to make different registration in the same Odoo e-commerce. Both partners will have the same acc_number.

I suggest to create a new contraint (partner_id, sanitazed_acc_number), but maybe this is not the point of this restriction.

What do you think?

**Comment by lmignon** [comment]
@antespi  IMO it's not safe to share an account number between different partners. In your case, your wife and you should be part of the same organisation and use the address of this organisation.
Moreover, when importing a bank.statement.line we expect to find only one partner linked to the account number.

My 2 cents,

lmi

**Comment by antespi** [comment]
@lmignon bank statement import process is a good reason for this constraint, we will tell this argument to our customer to justify this change.

Thanks for your answer
