### ISSUE TITLE
[8.0] support of attachements on statements

### ISSUE THREAD

**Issue by nbessi** [OCA/bank-statement-import#25]
I want to add the support of attachements to statement in the import process. They have to be added as a key of the statement dict.

What do you think ?

**Comment by lmignon** [comment]
@nbessi if attachment = ir.attachment the PR https://github.com/OCA/bank-statement-import/pull/21 provides this functionality

**Comment by nbessi** [comment]
@lmignon yes but the need is more complexe  want to be able to have many attachement on a statement. This will allows to store scan, signature that come along statement separatly

**Comment by lmignon** [comment]
@nbessi PR #21 should be extended to replace the import_file by a one2many relation on ir_attachment. The name of the ir_attachment could be use to describe the related file. (scan, signature,  ...) .

**Comment by nbessi** [comment]
@lmignon after disscuting with @fclementic2c it appears it should be a many2many

**Comment by lmignon** [comment]
@nbessi you probably are right.
