### ISSUE TITLE
Import statements for multiple accounts at once

### ISSUE THREAD

**Issue by sbidoul** [OCA/bank-statement-import#255]
Hi,

Are there known approaches to import files containing statements for multiple bank accounts at once? e.g. a zip file containing statements for different accounts.

If not we plan to develop two modules:

## account_bank_statement_import_multi

This one would 
- add a menu entry with a wizard to upload a statement file (without specifying the bank journal upfront) 
- some overridable method that `yield`s the individual statement files found in the uploaded file
- invoke the regular statement parsing and import method for each individual files

## account_bank_statement_import_multi_zip

- an override of the above split method that detects that a zip was uploaded and yields individual files found in the zip file

Thoughts?

**Comment by sbidoul** [comment]
cc/ @RobinetDenisAcsone

**Comment by pedrobaeza** [comment]
Isn't #213 from your colleague dealing with this?

**Comment by sbidoul** [comment]
@pedrobaeza no because that one still has the constraint (from the base module) that all statements in the file must be for the same bank account.

**Comment by pedrobaeza** [comment]
Ok, received. Curious that you go this way instead of exploring online sync.

**Comment by sbidoul** [comment]
> Curious that you go this way instead of exploring online sync.

@pedrobaeza you mean by creating some sort of zip file provider for https://github.com/OCA/bank-statement-import/tree/12.0/account_bank_statement_import_online?

**Comment by pedrobaeza** [comment]
Well, I was talking about removing files at all, as all European banks should now provide this information with webservices or similar thanks to PSD2 directive.

**Comment by sbidoul** [comment]
should, yes :)
