### ISSUE TITLE
Wrong start and end balance

### ISSUE THREAD

**Issue by sanderkruger** [OCA/bank-statement-import#28]
The OFX importer doesn't calculate the start and end balance correctly. Logically, the balance on a statement is the balance at the statement date. All mutations on the statement must have preceded the statement date (you can't see the future). Hence, the balance at the statement date is the end balance.

The code calculates start and end balance:

``` python
            'balance_start': ofx.account.statement.balance,
            'balance_end_real':
                float(ofx.account.statement.balance) + total_amt,
```

But it should rather do:

``` python
            'balance_end_real': ofx.account.statement.balance,
            'balance_start':
                float(ofx.account.statement.balance) - total_amt,
```

**Comment by pedrobaeza** [comment]
For which version?

**Comment by sanderkruger** [comment]
This is in the latest version, 8.0.1

**Comment by pedrobaeza** [comment]
This is a backport from v9 version Odoo version, so you should report in odoo/odoo the problem.

**Comment by sanderkruger** [comment]
Thanks, for the info. This issue is a duplicate of https://github.com/odoo/odoo/issues/3003
