### ISSUE TITLE
UnknownTimeZoneError on paypal PayPal Activity

### ISSUE THREAD

**Issue by estekadigital** [OCA/bank-statement-import#312]
I get UnknownTimeZoneError error importing a CSV file downloaded from Paypal. The reason is that Paypal's statement tz_value is CEST, which is not recognized by python3.7, therefor making a small change in the model would solve the issue. I just write the modification here instead of sending a PR as I do not have permission to send them.

Line 269 in file /account_bank_statement_import_paypal/models/account_bank_statement_import_paypal_parser

```
    @api.model
    def _normalize_tz(self, value):
        if value in ['PDT', 'PST']:
            return 'PST8PDT'
        elif value in ['CEST']:
            return 'CET'
        return value

```

**Comment by alexey-pelykh** [comment]
@estekadigital would it be possible to provide an anonymized CSV sample file to be embedded into the tests? And the country from which it originated.

**Comment by estekadigital** [comment]
Here goes a test, I replaced confidential data. The country is Spain.

[paypal_test.csv.txt](https://github.com/OCA/bank-statement-import/files/4930315/paypal_test.csv.txt)

**Comment by alexey-pelykh** [comment]
Thanks! I wonder why Paypal changed the format, as there was a Spanish statement in tests

**Comment by pedrobaeza** [comment]
I don't think the format has changed, but it has been exported from other place.

**Comment by estekadigital** [comment]
I followed the instructions on the readme to download the reports. This test was generated by Paypal from Reports > Activity download menu.
