### ISSUE TITLE
[account_bank_statement_import_online_afterbanks] Import statements from Afterbanks

### ISSUE THREAD

**Issue by rafaelbn** [OCA/bank-statement-import#348]
This is an issue to discuss how the development with the API of [Afterbanks](https://www.linkedin.com/company/afterbanks/) could be done and if there are more contributors interested.

We have in OCA already:

1) https://myponto.com -> [[ADD] account_bank_statement_import_online_ponto](https://github.com/OCA/bank-statement-import/pull/279) #279  contributions of Florent de Labarre @fmdl 

   https://myponto.com/en/reach

2) https://qonto.com -> [account_bank_statement_import_online_qonto](https://github.com/OCA/bank-statement-import/tree/12.0/account_bank_statement_import_online_qonto) contribution of @fmdl revieweg by @alexis-via " I made real-life tests with my qonto account: works fine." and @alexey-pelykh 

Our clients in Spain (one with multi-company in Portugal, France, UK) ask us for bank statement integration daily.

There are some points to take the decition "which provider"?

- Works with spanish banks (Mission: Impossible :smile: )
- Cost for customers (we have found 2€/month per IBAN and some [other plans](https://www.afterbanks.com/landings/landingEstandar.html)  )
- API integration:
     - https://app.swaggerhub.com/apis/Afterbanks/afterbanks-api/
     - https://www.afterbanks.com/api/documentation/es/
- PSD2 compliance ( https://psd2.afterbanks.com/ )

The other posibility is Unnax: https://www.unnax.com:
- https://www.unnax.com/pricing/
- https://sandbox.unnax.com/3.0/welcome/quick-start

With are general need in the OCA?

**Comment by alexis-via** [comment]
FYI, Qonto is a bank, it's not a bank account aggregator. So, the module that uses the Qonto API can only retrieve information from your Qonto bank account. Advantage : the API is free for all Qonto customers.
Ponto is a bank account aggregator, but I never used it.

**Comment by rafaelbn** [comment]
Yes @alexis-via , I know. I wanted just to note what is done arround. Thanks :smile: 

Ponto is a bank account aggregator list Afterbanks or Unnax.

Today 2020-10-22 This is the [list](https://docs.google.com/spreadsheets/d/13iuW36sVnskOibEnmya6CBivrXoWYF8YuO87_K5mAJQ/edit?usp=sharing) of banks supported by Afterbanks (Countries: AR, BE, BR, CA, CL, ES, FI, GB, GR, IT, MX, NL, PT, SE)

**Comment by fmdl** [comment]
Ponto is for FR, BE, NL bank

**Comment by rafaelbn** [comment]
> Ponto is for FR, BE, NL bank

Hi @fmdl it looks like Ponto is also for Spain

![2020-10-23_18-31-57](https://user-images.githubusercontent.com/8736623/97029776-2eba4300-155e-11eb-9deb-e617d1bc5bc7.png)

**Comment by rafaelbn** [comment]
Hello, it looks like https://github.com/OCA/bank-statement-import/pull/279 works for **Spanish banks** so i'm closing. The need is covered in this moments.
