### ISSUE TITLE
[Wish] Import bank statement from www.yodlee.com 

### ISSUE THREAD

**Issue by patel1008b** [OCA/bank-statement-import#352]

**Comment by patel1008b** [comment]
![CleanShot 2020-11-03 at 10 22 47@2x](https://user-images.githubusercontent.com/7733043/97951020-be61bc00-1dbe-11eb-9d5d-2ed471406da6.png)

**Comment by alexey-pelykh** [comment]
I'm looking into supporting bank data aggregators, but least amount of them are open to work in format that would fit OCA

**Comment by patel1008b** [comment]
Thanks a lot @alexey-pelykh , for your time to see and response on this.

It would be great that If we have yodlee because it covers much more banks.

Let me know if I can help for this.

Regards,
