### ISSUE TITLE
[10.0][Error] Could not make sense of the given file

### ISSUE THREAD

**Issue by nagybal** [OCA/bank-statement-import#358]
I am trying to import an OFX statement. The Odoo server log shows:

> "POST /web/dataset/call_button HTTP/1.1" 200 -
> "POST /web/dataset/call_kw/account.bank.statement.import/default_get HTTP/1.1" 200 -
> "POST /web/dataset/call_kw/account.bank.statement.import/onchange HTTP/1.1" 200 -
> "POST /web/menu/load_needaction HTTP/1.1" 200 -
> "POST /web/dataset/call_kw/account.bank.statement.import/create HTTP/1.1" 200 -
> "POST /web/dataset/call_kw/account.bank.statement.import/search_read HTTP/1.1" 200 -
> "POST /web/dataset/call_button HTTP/1.1" 200 -
> "POST /web/dataset/call_kw/account.bank.statement.import/search_read HTTP/1.1" 200 -
> "POST /longpolling/poll HTTP/1.1" 200 -

What does this mean?

**Comment by alexey-pelykh** [comment]
That it could not parse the file, e.g. maybe you don't have a proper module installed. Please try to reproduce issue on runbot first

**Comment by nagybal** [comment]
On runbot I get the same. The OFX file I am using got converted from an XML file using this tool: https://github.com/kedder/ofxstatement

What could be wrong with the file then?

**Comment by alexey-pelykh** [comment]
Unfortunately, that question can not be answered w/o examining the file itself.

**Comment by nagybal** [comment]
@alexey-pelykh I did emaill You the file. Please take a look!

**Comment by alexey-pelykh** [comment]
@nagybal thanks, I'll get back to you during the weekend

**Comment by nagybal** [comment]
@alexey-pelykh a kind reminder

**Comment by alexey-pelykh** [comment]
@nagybal I've looked into the file, and it's not compatible (in more than one way) with https://github.com/jseutter/ofxparse that's being used by the module. According to https://github.com/gyp/ofxstatement-otp, OTP Bank Hungary can export CAMT.053 format, and I'd give it a shot instead of converting that to OFX if there's such possibiity.

**Comment by nagybal** [comment]
I have the option to export in camt.052.001.02 according to the ISO20022 (UNIFI) standard. I still get errors. I guess it must be version CAMT.053

`bigb@Nagys-iMac Downloads % ofxstatement convert -t iso20022 20201231.CAM huf12.ofx
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/ofxstatement", line 33, in <module>
    sys.exit(load_entry_point('ofxstatement==0.7.1', 'console_scripts', 'ofxstatement')())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ofxstatement/tool.py", line 195, in run
    return args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ofxstatement/tool.py", line 166, in convert
    statement = parser.parse()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ofxstatement/plugins/iso20022.py", line 46, in parse
    self._parse_statement_properties(tree)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ofxstatement/plugins/iso20022.py", line 63, in _parse_statement_properties
    assert iban is not None
AssertionError
`

**Comment by alexey-pelykh** [comment]
@nagybal reach me out directly with a sample file and maybe let's look into it deeper
