### ISSUE TITLE
Bank statement import fails (csv.) | Odoo CE V13

### ISSUE THREAD

**Issue by ThorOdoo** [OCA/bank-statement-import#368]
Hello,

tried to import our bank statement via csv today (using Odoo CE V13 with OCA modul). When clicking on "Import" following error message appears: 
"This file doesn't contain any transaction for account *Our IBAN*. If it contains transactions for more than one account, it must be imported on each of them."
The CSV file contains the IBAN (as bank account column) and the mapping also contains all the other reference names given in the csv table.

Can you say what the problem might be?

**Comment by pedrobaeza** [comment]
Which module do you mean? Is from this repository?

**Comment by ThorOdoo** [comment]
we installed the OCA account_bank_statement_import_txt_xlsx version 13.0.1.0.4

**Comment by pedrobaeza** [comment]
OK, I let this opened for contributors of such module to answer.

**Comment by rpsjr** [comment]
Looks like the v13 doesn`t have the engines needed to parse the files.

**Comment by alexey-pelykh** [comment]
Does the issue reproduce on a runbot? It's not much possible to say w/o a data sample and the mapping that you have. Likely, either it's something uncommon with the file or mapping is wrong.

**Comment by rpsjr** [comment]
> Does the issue reproduce on a runbot? It's not much possible to say w/o a data sample and the mapping that you have. Likely, either it's something uncommon with the file or mapping is wrong.

All right, under runbot everything works fine. Thats certainly a local installation problem. 

http://3482513-13-0-9cfee1.runbot2.odoo-community.org/web#action=bank_statement_reconciliation_view&active_id=1&cids=&menu_id=98

Thx alexey-pelykh.
