### ISSUE TITLE
ALL VERSIONS: CAMT ReversalIndicator (RvslIdct) needs to inverse the amount sign

### ISSUE THREAD

**Issue by Guenzn** [OCA/bank-statement-import#375]
We import camt files of german Sparkasse generated by SFIRM. Very frequently there is a transaction (ntry) marked as reversal and of type debit, which refers to another debit transaction. At the banking website and of corse at SFIRM we can see, that we get the money back, but in odoo it will be created with negative amount (correct for debit). Also if a reversal transactions is of type credit, at SFIRM and the bank website we see it as a negative transaction, but in odoo it's created with positive sign. 

It seems that when importin an transaction with reversal indicator = True, we need to inverse the sign of the amount.

**Comment by TeoGoddet** [comment]
I'm mot sure it's enough, because it works well now when a credit is a reversal of a debit

**Comment by Guenzn** [comment]
I fixed it for our customer by overwriting  object 'account.bank.statement.import.camt.parser' parse_amount method and inverse the sing of the amount if RvslInd is true.

`class CamtParser(models.AbstractModel):
    """Parser for camt bank statement import files."""
    _inherit = 'account.bank.statement.import.camt.parser'

    def parse_amount(self, ns, node):
        """Parse element that contains Amount and CreditDebitIndicator."""
        amount = super(CamtParser, self).parse_amount(ns, node)
        # INVERSE AMOUNT SIGN IF REVERSAL INDICATOR IS TRUE
        if amount:
            reversal_node = node.xpath('ns:RvslInd', namespaces={'ns': ns})
            if reversal_node and reversal_node[0].text == 'true':
                amount *= -1
        return amount`

**Comment by TeoGoddet** [comment]
We could fix it upstream, but we need to be sure it doesn't introduce more bugs, could you provide an sample camt file ?

**Comment by Guenzn** [comment]
Sorry, currently i havent a sample camt file, but in the module there is already one: https://github.com/OCA/bank-statement-import/blob/257ab6797ded862e99b089963448a67821c770b2/account_bank_statement_import_camt_oca/test_files/test-camt053#L113 

ISO definition: Indicates whether or not the entry is the result of a reversal.
Usage: This element should only be present if the entry is the result of a reversal.
If the CreditDebitIndicator is CRDT and ReversalIndicator is Yes, the original operation was a debit entry.
If the CreditDebitIndicator is DBIT and ReversalIndicator is Yes, the original operation was a credit entry.
