### ISSUE TITLE
[12.0][Migration][Error] account_bank_statement_import_txt_xlsx 

### ISSUE THREAD

**Issue by mrgoetz** [OCA/bank-statement-import#377]
Hi guys, I have issues to migrate account_bank_statement_import_txt_xlsx from 11.0 to 12.0.
The sql Script in migrations/12.0.2.0.0   uses the non existing tables account_bank_statement_import_map and account_bank_statement_import_map_line. What is missing here ?
Thanks for help
Cheers Michael

**Comment by alexey-pelykh** [comment]
Try to upgrade to 12.0.1.0.0 first and then to 12.0.2.0.0, there was a major refactor in v12.0.2.

**Comment by mrgoetz** [comment]
Thanks Alexej, that worked for me. I divided the migration of account_bank_statement_import_txt_xlsx in 2 steps:
11 to 12.0.1.0.1 and then 12.0.1.0.1 to 12.0.2.0.0

 You can close this issue or I will do it later, if you don't mind.
Cheers Michael
