### ISSUE TITLE
[12.0] ponto : it doesn't import ending and starting balance.

### ISSUE THREAD

**Issue by pasgou** [OCA/bank-statement-import#379]
When collecting data from MyPonto, statement doesn't have correct ending and starting balance.
I have a propal here to be reviewed 
https://github.com/OCA/bank-statement-import/commit/b28ef5137056103ef4b2b84792d230440e38583d

**Comment by pedrobaeza** [comment]
You are tricking the meaning of such fields, as the module is adding constantly new transactions to the same bank statement, so there's no real ending balance. If you compute it from the transactions, the meaning of the field as checking point is lost.

**Comment by pasgou** [comment]
Ok
But not to have a ending balance make the view of the bank account meaning less as it is always to 0 (zero).
I search a means where the ending balance (which is an account attribute value) could be write at the end.
In my propal, the field which is computed is the account starting balance, with the trouble you wrote about.

What about only send the account ending balance with the transaction values at the end of the processus, without get or compute a starting balance?

**Comment by pedrobaeza** [comment]
For me, it's the same trick. I just do monthly statements, and when the month is gone, I check theoretical ending balance, and copy it to ending balance. This is tricking as well, but not letting users to think that the ending balance is real instead of being computed.

Imagine the following scenario:

- 3 transactions are downloaded, with an ending balance of 100 €.
- You delete one transaction for 20 € > ending balance should be manually changed to 80 € to match for closing the stament.
- Now a new transaction is downloaded, and if the ending balance is auto-computed, it won't be valid as you have mangled the list.

**Comment by pasgou** [comment]
Ok, I understand.
But we have always the same trouble when we show full accounting behaviour and have bank cards.
The graphic with the account balance will be wrong.
I was inspired by the account_bank_statement_import_online_paypal : this one seems to compute starting and ending balance, cause we rarely delete transactions (it could be the case when we begin to use the module and there are some transactions already written before).
About the code, could I have your opinion, as I am a beginner : the result of the processus I expected was to collect the account ending balance. I didn't anticipited the trouble with starting balance. Could you say me if it's the case, without considering if it's a good or a bad idea.

**Comment by alexey-pelykh** [comment]
`account_bank_statement_import_online_paypal` does not compute ending balance, it takes balance after last known transaction. Bad idea is to get starting balance and add sum of all transactions, that's a fake.

**Comment by pasgou** [comment]
But what I wrote is to get ENDING balance, as this is the only information available without any computation.

Paypal module compute STARTING balance compare to ending balance, and it's what I proposed to do.

So, or what I wrote doesn't search ending balance as expected and I would like you to help me to understand why, or I obtain the good result and it's ok.

Ending balance is supposed to change, or not, each time you pull the transactions, having as consequence to change the ending balance in Odoo interface, and that's the result I want to obtain, even if sometimes the accountant have to do is job : audit the operations and correct false informations.

**Comment by alexey-pelykh** [comment]
@pasgou if possible, please provide link to the PR in question, it seems the branch is gone?

**Comment by pasgou** [comment]
@alexey-pelykh 
In this version, I integrated a computation of starting balance which is perhaps useless, but I don't understand why and where (Pedro says that it's a check point !?)
https://github.com/OCA/bank-statement-import/commit/b28ef5137056103ef4b2b84792d230440e38583d

**Comment by alexey-pelykh** [comment]
@pasgou if you want PR to be reviewed, it needs to exist:

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
