### ISSUE TITLE
[13.0] Currency issue : wrong amount taken

### ISSUE THREAD

**Issue by d4e-ch** [OCA/bank-statement-import#385]
Hi !

We have seen some issues in the amount of the imported CAMT.53 when currency is EUR instead of CHF.
It takes the EUR amount as the CHF amount, instead of taking the CHF amount, which is also in the file data.

Thanks !

**Comment by TeoGoddet** [comment]
+1
 
The module use this field (Amt) : it contains the amount in the payment currency, not in the bank account currency
![image](https://user-images.githubusercontent.com/9885447/137583282-b48f973c-7332-410c-be5f-e227b3ca753d.png)

We should look a this field (AmtDtls)
![image](https://user-images.githubusercontent.com/9885447/137583320-aa699036-b3a4-4f15-8fa3-9107038c0aab.png)

I will try to submit a PR to correct the statement as soon as possible,
but as a second step, should we record the exchange rate somewhere (for reconciliation or whatever ? )
