### ISSUE TITLE
[14.0] Swiss CAMT54 Problem with currency.

### ISSUE THREAD

**Issue by anedisi** [OCA/bank-statement-import#387]
Swiss CAMT files don't contain currency under the Acct/Ccy. 
The workaround for CAMT53 files is that it looks in the Bal/Amt@Ccy so those work.

account_statement_import_camt/models/parser.py
LINE: 206
```
self.add_value_from_node(
    ns, node, ["./ns:Acct/ns:Ccy", "./ns:Bal/ns:Amt/@Ccy"], result, "currency"
) 
```

The problem is that in the CAMT54 files there is no Bal element, so the "backup" could not work.
The result is that it throws an error that there is no currency when trying to import a CAMT54 file.
The solution could be to pull the currency from the first Entry, or is there another suggestion ?

**Comment by ph-obs** [comment]
Hey @anedisi. I stumbled upon your issue. I am facing the same problem. Did you find any solution for it or did you receve any feedback to this ticket?
My quick-and-dirty solution would be to hardcode the currency_code (if missing) to default to the companies main currency but I don't know if there is any better solution to do it...

Thanks.

**Comment by anedisi** [comment]
Hello, you can see my pull request. I added the option to pull currency from Entry because the first two options don't exist in swiss esr camt54 files. 
https://github.com/OCA/bank-statement-import/pull/388/files

`Diese Meldung enthält das Element «Balance» nicht.`
