### ISSUE TITLE
Revolut business online import

### ISSUE THREAD

**Issue by ayushin** [OCA/bank-statement-import#390]
Hi,

Is anybody working on this by any chance?

Please upvote this issue if you are interested.

**Comment by alexey-pelykh** [comment]
Not to my knowledge

**Comment by pedrobaeza** [comment]
Nobody has expressed in public that intention.

**Comment by ayushin** [comment]
The authentication flow is a bit of a hassle, you need to generate a key pair, upload that that public key to revolut, then start auth flow to authorise the app with revolut and after that exchange one jwt for another, but after that it's straighforward

**Comment by ayushin** [comment]
https://developer.revolut.com/docs/manage-accounts/#get-started-get-started-make-your-first-api-request-1-upload-your-certificate
