### ISSUE TITLE
Transferwise saving jars import

### ISSUE THREAD

**Issue by llabusch93** [OCA/bank-statement-import#393]
Hello folks,
with the new saving jar feature in Wise business accounts, it would be handy to also be able to sync the statements of those. So if you are having one to save for your monthly or quarterly VAT declaration, we need to reflect the moves also in the accounting in Odoo.

Any +1s for this?

**Comment by alexey-pelykh** [comment]
There's a chance someone from community would consider contributing this feature. I don't really have it on my roadmap as of today unless someone would sponsor it.
