### ISSUE TITLE
[13.0] ponto : it doesn't import transactions with Value date after Execution date.

### ISSUE THREAD

**Issue by dortunbo** [OCA/bank-statement-import#401]
Hi,

When collecting data from MyPonto, I've noticed that transactions having the Value date after the Execution date (e.g. Vd=02/07/21, Ed=30/06/21) are not imported. Is this a normal behavior of the module? 

Thanks,

**Comment by MirkazFMP** [comment]
Up, I'd like a reply as well.

**Comment by clementmbr** [comment]
+1 !

**Comment by NL66278** [comment]
I think the problem might be due to a mismatch between the general logic for online bank statements, to retrieve the records per day, and the way Ponto selects them between identifiers.
