### ISSUE TITLE
[v13] Bank Statement Format

### ISSUE THREAD

**Issue by hgati** [OCA/bank-statement-import#409]
The form of the bank we use is as follows.
The debit/credit column is devided with two.

![이미지 6](https://user-images.githubusercontent.com/6913728/130158270-8364194f-183b-4e3a-88a0-870e8a79a168.png)

How to specify in single column the Debit/credt column on Sheet mapping?

![이미지 7](https://user-images.githubusercontent.com/6913728/130158674-bf73fc7a-5153-4955-a64f-c52c71b3ff33.png)

Thanks.

**Comment by alexey-pelykh** [comment]
Hi @hgati! Unfortunately this feature is not supported. For rare cases I've seen similar format, I've ended up adding extra column to the statement that would collect data from both with formula `=IF(DEBIT>0,-DEBIT,CREDIT)` or similar

**Comment by hgati** [comment]
> Hi @hgati! Unfortunately this feature is not supported. For rare cases I've seen similar format, I've ended up adding extra column to the statement that would collect data from both with formula **`=IF(DEBIT>0,-DEBIT,CREDIT)`** or similar

`=IF(DEBIT>0,-DEBIT,CREDIT)` 

![이미지 10](https://user-images.githubusercontent.com/6913728/130193407-b4e09068-880b-4d84-99fb-f7c95a8eba49.png)

This formula is awesome idea I never thought.
Thanks. **You're Great.**
