### ISSUE TITLE
Support for nordigen.com

### ISSUE THREAD

**Issue by ayushin** [OCA/bank-statement-import#412]
This is a free open banking API which supports many business accounts, including Wise and Revolut

This could replace https://github.com/OCA/bank-statement-import/issues/402

Probably an effort better spent.

**Comment by alexey-pelykh** [comment]
A PR to introduce module that supports nordigen.com would be welcomed if you want to make one.

**Comment by ayushin** [comment]
I wish I had the time.

**Comment by ayushin** [comment]
They also have a great python starter app:

https://github.com/nordigen/nordigen-python

**Comment by ayushin** [comment]
They just published a new python library:

https://github.com/nordigen/nordigen-python
