### ISSUE TITLE
Installing this module destroys generic import module

### ISSUE THREAD

**Issue by Stephanisk** [OCA/bank-statement-import#428]
Hi,

Installing this module : account_statement_import_online
leads to destruction of the generic import module: om_account_bank_statement_import

This is quite a disappointment. As this module didn't work as we needed, we uninstalled and wanted to use the generic module again. Sadly enough this module now doesn't respond anymore to upload file. Upon clicking upload the upload screen simply disappears. 

First time ever I have an issue with modules from OCA, very unfortunate as we have to now manually create bank statements as uploading is no longer possible.

Pls review your code here so it doesn't irreparably damages other modules.

Some help would be appreciated.

**Comment by pedrobaeza** [comment]
You are not indicating the version, but anyways, the other module is not a generic one, but a custom one and it's not OCA, and it's probably incompatible with the OCA one, but if I have to bet, I would say what you call generic is which have a questionable implementation. Anyways, it's not a problem of OCA, so closing.
