### ISSUE TITLE
account_statement_import and account_bank_statement_import incompatible?

### ISSUE THREAD

**Issue by baimont** [OCA/bank-statement-import#430]
Hi there!

I recently had a problem installing modules on a database.

I wanted to install 2 modules : account_accountant and account_statement_import but this is impossible because account_accountant leads to the installation of account_bank_statement_import and since demo data are the same in account_statement_import and in account_bank_statement_import the installation leads to an error : 
```
ERROR: duplicate key value violates unique constraint "res_partner_bank_unique_number"
DETAIL:  Key (sanitized_acc_number, company_id)=(10987654322, 1) already exists.
```

So I have two questions:
1) Are account_statement_import and account_bank_statement_import supposed to be incompatible? (shouldn't this be stated in the readme of account_statement_import?)
2) Is it normal that demo data in account_statement_import and account_bank_statement_import are the same?

Thanks

**Comment by pedrobaeza** [comment]
Yes, they are incompatible as both derives from the same origin, but `account_accountant` doesn't depend on such module. It's only auto-install. Uninstall it manually and that's all.
