### ISSUE TITLE
Module can't be installed in Odoo 8

### ISSUE THREAD

**Issue by Whytehorse** [OCA/bank-statement-import#45]
I'm running the nightly 8.0 stable odoo and when I try to import this module it gives an error. I have downloaded the 8.0 branch zip file and tried installing it several different ways. There is some missing field that shows up in the server log file that says:
Error details:
Field `module_base_bank_account_number_unique` does not exist

**Comment by bambid** [comment]
Is there a solution for this problem? i have the same problem.

Kind Regards
bambid

**Comment by pedrobaeza** [comment]
This is something in your deployment, but the module works correctly.
