### ISSUE TITLE
Unable to install module "account_statement_import_online" because an external dependency is not met: Python library not installed: odoo_test_helper

### ISSUE THREAD

**Issue by Richiejerry** [OCA/bank-statement-import#480]
Having an issue installating the account_statement_import_online on Odoo 14 community, I am getting the following error:

Unable to install module "account_statement_import_online" because an external dependency is not met: Python library not installed: odoo_test_helper

**Comment by alexis-via** [comment]
It seems that the solution is almost written in the error message:

```
sudo pip3 install odoo-test-helper
```
and try to install the module again.
