### ISSUE TITLE
Nordigen Intergration

### ISSUE THREAD

**Issue by ghost** [OCA/bank-statement-import#491]
**Is your feature request related to a problem?**
The existing bank import providers seem to lack support for the UK providers and charge a fee for using their services.
Nordigen which is now owned by GoCardless offers a Free service which caters for a good chunk if not the entire EEA's open banking providers.

The free access is account information only with premium addons available which would be out the scope of this repo.

**Describe the solution you'd like**
A Provider to be created to import the statements using the open banking protocols that is cost effective (in this case free) and all inclusive.

**Describe alternatives you've considered**
Manual Entry (Tedious and error prone)
PayPal only (Not using a bank get's paypal to impose restrictions)
My Ponto (Doesn't support any UK providers)
old school file imports seem to be not compatible with some of the more modern fintechs.
Not use ODOO (Really don't like that idea).

**Additional context**
Nordigen supports 2392 banks all across the EEA from what I can tell: https://nordigen.com/en/coverage/
Fully Openbanking Compliant
Free for relevant purposes: https://nordigen.com/en/pricing/
New python library on github: https://github.com/nordigen/nordigen-python
The fact it's now owned by GoCardless also opens up a lot of opportunities for cost effective opensource Direct Debits, Sepa and ACH services without the Odoo Enterprise Subscription requirement.

**Comment by jayo2005** [comment]
Hi have you had any progress with Nordigen. I am looking into that at the moment.

**Comment by ghost** [comment]
@jayo2005 I have not had chance to even look, yet work has been full on. If you're up for taking a stab at it I would be happy to test it.

**Comment by ayushin** [comment]
Awesome, I'm happy to help! Either with testing or PR if needed.

https://github.com/OCA/bank-statement-import/issues/412

**Comment by ayushin** [comment]
so i see there's a PR but is anybody working on it?

**Comment by ayushin** [comment]
@JordiBForgeFlow

**Comment by JordiBForgeFlow** [comment]
@ayushin this PR implements the nordigen integración and works https://github.com/OCA/bank-statement-import/pull/496

**Comment by joseant** [comment]
Any news about this?

**Comment by ayushin** [comment]
what is needed to get this finished?

**Comment by Entrepreneur-AJ** [comment]
@ayushin Lost access to the account I originally posted this with, https://github.com/OCA/bank-statement-import/pull/496 seems to work after removing the sandbox id from the code so this one needs closing.

**Comment by Entrepreneur-AJ** [comment]
@jayo2005 @joseant @pedrobaeza PR #592 ready for review
