### ISSUE TITLE
MyPonto - Import statements but do not it's movements in specific dates 

### ISSUE THREAD

**Issue by belisac** [OCA/bank-statement-import#492]
## Module
bank-statement-import/account_statement_import_online_ponto/

## Describe the bug
From 01/07 to 18/07 Odoo has created each statement but each movements for those days it hasn't. It has been checked and the information it's in MyPonto account, but it's not in Odoo

## To Reproduce
Community Version 12 and 13 
1.  Go to Invoicing > Configuration > Bank Accounts 
2. Select specific bank accounts
    Launch Actions > Online Bank Statements Pull Wizard
3.  Configure date interval and click Pull
    
**Expected behavior**
Get the movements in these statements from this period as normally do.

Thanks in advance for your attention,

Regards

**Comment by NL66278** [comment]
This PR is intended to solve this for 12.0. https://github.com/OCA/bank-statement-import/pull/493

**Comment by NL66278** [comment]
Set the next run date in the provider to a date in the future and wait for the next run.

A permanent solution will come from this PR: https://github.com/OCA/bank-statement-import/pull/498

**Comment by NL66278** [comment]
@belisac Check that you have the latest 12.0 code and you have upgraded your database. (You should have a menu option: Reporting ==> Management ==> Show Ponto buffer in the invoices app when full auccounting option active for user).

Retrieve missing data using the wizard that can be called from the actions in the journal form.

Let me know if this helps.

**Comment by belisac** [comment]
Dear @NL66278 

Thank you answer and your orientation. Let me congrats you for excellent job with this issue. I already upgraded that the database. I tested again the problem that begins this issue and from 1 day and using the wizard, every single movement was import successfully from MyPonto to Odoo! Kudos to you! 

I checked the menú and its very interesting as a guide and control the movements imported! Thaks for that improvement.

There is one "but" that the user already reported. Today 06/10 was created only one statement with the correspond movement for one account (fig 12.png)
![12](https://user-images.githubusercontent.com/44980860/194296692-c6b2e644-145d-4c19-bc73-0e1808991605.png)

The rest of account the statements were not created today 06-10. We can see only until 05-10 
![13](https://user-images.githubusercontent.com/44980860/194296633-8ebce35e-ae85-48a8-b29c-b758491b8ee9.png)
![14](https://user-images.githubusercontent.com/44980860/194296730-a5af0db2-83d1-432e-8def-45afcffe0ea9.png)


This issue were not happening before and was working right. Could please let me know why? And if there is something new that I have to be aware of?

Thanks in advance for you attention, 

Regards! 

Belisa

**Comment by NL66278** [comment]
Check wether there are transactions in the ponto buffers for those accounts. Also check the next_run date for the providers. You might be helped by this PR I created today: https://github.com/OCA/bank-statement-import/pull/507

**Comment by belisac** [comment]
Thank you for your answer.

I checked and the Ponto buffers appears only one for the account updated. (1)

About next-run date the field shows behind the actual hour, (2) 

 I will try to follow the PR you have created, please let me know if there something I should be aware

Regards 

(1) 
![Ponto-Buffer-Odoo](https://user-images.githubusercontent.com/44980860/194308141-bf52aea4-0765-407f-a59b-063ae3a5a7fb.png)

(2)  
![18](https://user-images.githubusercontent.com/44980860/194308720-452c0243-4354-4e82-be74-5c327ffeb1d5.png)

**Comment by NL66278** [comment]
In what timezone do you operate, and how far behind or ahead of UTC is that timezone?

**Comment by belisac** [comment]
My Time Zone is in Madrid, Spain   (GMT+2)
