### ISSUE TITLE
Duplicate Bank statement line 

### ISSUE THREAD

**Issue by belisac** [OCA/bank-statement-import#499]
## Module
The name of the module that has a bug.
account.bank.statement

## Describe the bug
There some account.bank.statement lines that are duplicating in an extract without reason so far. If we check from de the bank side there not such movements that we are seen in Odoo. So obviously this creates re-work and mes when your are trying to reconcile the journal item

## To Reproduce
**Affected versions**: 14.0

1. Go to Bank Statements and review the movements and the show 2 times each.  
2.
3.

**Expected behavior**

See just the statements lines that we should and synchronize with the bank

Thanks in advance for your help! 
Regards

![2](https://user-images.githubusercontent.com/44980860/192516258-764e808c-d13a-4953-814e-f60bb52f1175.png)

**Comment by NL66278** [comment]
@belisac Please provide more information. What kind of import are you using? What are the actions you take before you see this?
