### ISSUE TITLE
Manual creation of temporary file

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-statement-import#5]
I'm just looking at the code of account_bank_statement_import_ofx/account_bank_statement_import_ofx.py line 33, and I see:

```
        try:
            tempfile = open("temp.ofx", "w+")
            tempfile.write(base64.decodestring(data_file))
            tempfile.read()
            pathname = os.path.dirname('temp.ofx')
            path = os.path.join(os.path.abspath(pathname), 'temp.ofx')
```

the code creates a temporary file "temp.ofx", without using the proper library to create a temporary file. I am not an experienced developper, but isn't it a very very bad thing ? I have always been tought that when we create a temporary file we should always use the appropriate library to manage it, so avoid security issues and other problems.

**Comment by pedrobaeza** [comment]
This is direct code from Odoo, because we don't want to change nothing to easy direct upstream updates. Indeed, it's not the best option.

For v7, the module I did uses proper API: https://github.com/OCA/bank-statement-reconcile/blob/7.0/account_statement_ofx_import/parser/ofx_parser.py#L53

**Comment by alexis-via** [comment]
In fact, I found out that it is the cause of a bug and I could not import because it failed on the line

```
tempfile = open("temp.ofx", "w+")
```

and my use had the message "Please check OFX file format is proper or not.". I first thought that this issue was caused by a bad OFX file, but later found that the exception was raise by the open().

It is on a server that runs both test databases and the production database from the same odoo directory. I updated the code to use the Tempfile lib, and the bug was solved. I'll do a PR to fix this.

So I'll prepare a PR to fix this issues, because

**Comment by sbidoul** [comment]
Gasp. That's not nice code indeed.

I'd suggest you do the PR towards odoo/master first since what we have here is a backport.

**Comment by alexis-via** [comment]
@sbidoul I had a look at master, and this piece of code has already been changed, and they now use StringIO.StringIO(data_file). So maybe we will have to do a new backport.
