### ISSUE TITLE
OFX file with non-standard ACCTID

### ISSUE THREAD

**Issue by augustodinizl** [OCA/bank-statement-import#537]
**Module**
account_statement_import_ofx

**Describe the bug**
Here in Brazil, we suffer from a non-standatization from a lot of bank institutions when the matter comes to reports, even with .OFX ones (yeahp, really 😄)
Some banks use the ACCTID tag for OFX account statements, with just the account number, others, use "account no."-"digit" another ones, use a combination "agency"-"account"-"digit" that's a nightmare for us

**To Reproduce**
Affected versions: Community 14.0 and 12.0
Import a given bank .ofx with that as example
![image](https://user-images.githubusercontent.com/25938418/209014997-0d900808-d7f8-4d0d-ba81-903b982e3374.png)
and see the error prints, since the thag ACCTID of the file is different from the Account number stored in odoo.

**Expected behavior/ changes proposal**
Maybe, if in the import module, we insert a field called ACCTID in the bank account in odoo, and make that field be used as verification method (if filled) instead the account number, i believe that issue can disappear.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

Thanks in advance for your help and comments,

Regards,

Augusto

FiY, sorry about my poor english...

**Comment by marcelsavegnago** [comment]
https://github.com/OCA/bank-statement-import/pull/539

**Comment by augustodinizl** [comment]
Closed as #539 solves it
