### ISSUE TITLE
[14.0] account_statement_import: Button "Import Statement (OCA)" only shown in debug mode with assets

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-statement-import#597]
Steps to reproduce the bug on odoo v14:
1) install the module account_statement_import
2) add yourself to the group "Show full accounting features"
3) go to the invoicing dashboard : there is no button "Import Statement (OCA)" at the top
4) enable debug mode with assets
5) go to the invoicing dashboard again : the button "Import Statement (OCA)" now appears at the top

![account_statement_import-bug_button](https://github.com/OCA/bank-statement-import/assets/1157917/ae384f30-58ca-4718-882b-6f642ae9171b)

@etobella do you have an idea about this bug ? It seems you are the one who added that useful button !

**Comment by rvalyi** [comment]
(@alexis-via we have this issue with our DS customer BTW, I teached them this workaround.)

**Comment by alexis-via** [comment]
@rvalyi Yes, the workaround works, but we need to understand the root cause and fix it! It's the purpose of this bug report!

**Comment by etobella** [comment]
@alexis-via I see the problem. I proposed a simple patch. Can you review it? it worked properly on local

**Comment by alexis-via** [comment]
@etobella Thank you very much for the fix ! I tested it and it works well. I approved the PR.
