### ISSUE TITLE
[8.0] base_bank_account_number_unique: Not valid for multi-company

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/bank-statement-import#60]
If you install the module _base_bank_account_number_unique_ and you have multi-company, you can find that you have a customer in two companies that needs to define 2 res.partner.bank records, one for each company, and this module prevents it.

I think the unique condition should be done for both the sanitized account bank number and the company_id.

**Comment by pedrobaeza** [comment]
cc @hbrunn

**Comment by legalsylvain** [comment]
agree.

**Comment by hbrunn** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:
