### ISSUE TITLE
[V15] Error when trying to import CSV (or XLSX) bank statement

### ISSUE THREAD

**Issue by FreezeS** [OCA/bank-statement-import#603]
Hi guys,

Running Odoo 15.0-20230517 (Community Edition).
I'm trying to import a bank statement and keep getting a very unhelpful error.

Module installed:
![image](https://github.com/OCA/bank-statement-import/assets/2807003/a60869c4-4270-4fc0-ad82-c5c0ff6c6fc6)

The first line of the file is this:
    01.05.2023; Detalii: INREGISTRARE DOBANDA OVERDRAFT;-550,71;-113324,64

Created manual mapping:
![image](https://github.com/OCA/bank-statement-import/assets/2807003/d96cc718-9bff-45b7-a1a8-1a1d825f2401)

Created automatic mapping (Action - Import Mapping):
![image](https://github.com/OCA/bank-statement-import/assets/2807003/ffa20082-6477-476d-ac63-f13867c45293)
![image](https://github.com/OCA/bank-statement-import/assets/2807003/d21ff5cb-ae40-4acc-a142-485c7b06ccde)

I tried to import the CSV using both mappings:
![image](https://github.com/OCA/bank-statement-import/assets/2807003/c5bb57c6-34d5-4e96-9bdf-3e67c3202d35)
![image](https://github.com/OCA/bank-statement-import/assets/2807003/636fe201-1aa7-45d4-9be1-6fcc24c3d471)

And got the same error:
This bank statement file format is not supported.
Did you install the Odoo module to support this format?

![image](https://github.com/OCA/bank-statement-import/assets/2807003/a0d7c89c-c97b-4596-b504-19ba2e655790)

I tried for CSV and XLSX
When I run Import Mapping it sees all the fields and the mapping is generated properly but the import itself fails.
A more detailed error would help so at least I know where to look.

**Comment by denilson020898** [comment]
You may want to check your csv or excel file.
For my case, decimal number must not be null and the date format must match the setting template.

Try make your csv as the following, from the code sample

"Date","Label","Debit","Credit","Balance","Partner Name","Bank Account"
"12/15/2018","Credit 20.00","0.00","20.00","-10.00","John Doe","123456789"
"12/15/2018","Credit 13.50","0.00","-13.50","-23.50","John Doe","123456789"
"12/15/2018","Debit 33.50","-33.50","0.00","10.00","Azure Interior",""
"12/15/2018","Debit 1500","1,500.00","0.00","1,510.00","Azure Interior",""

**Comment by FreezeS** [comment]
So there are 3 issues here:
1. The file format is not correct. There is no documentation about what the correct format is.
2. The error message is very cryptical and misleading. It sends me to search for a module that I might need to install to interpret the file format.
3. The automatic mapping generates the wrong mappings since the file can't be imported using the generated mapping. It also doesn't throw any error so the user believes the mapping generation is successfull.

**Comment by denilson020898** [comment]
> So there are 3 issues here:
> 
> 1. The file format is not correct. There is no documentation about what the correct format is.
> 2. The error message is very cryptical and misleading. It sends me to search for a module that I might need to install to interpret the file format.
> 3. The automatic mapping generates the wrong mappings since the file can't be imported using the generated mapping. It also doesn't throw any error so the user believes the mapping generation is successfull.

Agreed, I was aware of this when comparing the test example with my bank statements.
