### ISSUE TITLE
Every line item is converted to a separate bank statement

### ISSUE THREAD

**Issue by raarts** [OCA/bank-statement-import#61]
I don't know of this an importer issue, or an issue of the generic module. I'd like to have one bank statement created for the entire import file.

**Comment by pedrobaeza** [comment]
That's the normal behaviour (one file > one statement), so you should see the specific import. You haven't also indicated the version.

**Comment by raarts** [comment]
I'm sorry, maybe I was not clear. I imported one file, and it generated 10 bank statements in Odoo. (using 8.0). I used the CAMT format importer. The one file contained 10 payments.

**Comment by pedrobaeza** [comment]
The problem is then with the CAMT importer.

**Comment by raarts** [comment]
Oops, closed inadvertently. Thought there was another place to go for CAMT importer, but I guess this is it.

**Comment by pedrobaeza** [comment]
Yeah, let's wait for the answer of the authors of that module.

**Comment by ploegvde** [comment]
For every day the import makes a separate bank statement. This is normal behavior. It is the way a camt file is formatted.

**Comment by raarts** [comment]
Erwin,

I understand thanks, you may want to mention this somewhere in the README. The reference ID of each statement is formatted differently from usual Odoo bank statements, and I bet they look like gibberish to clients. Is that intentional/configurable?

**Comment by ploegvde** [comment]
To be clear, i'm not the author of the module.

The reference ID is directly taken from the camt file itself. Field <id>. When you create a manual bank statement, there is no reference from a file and then the sequence from the journal is used. And to answer your question: It is not configurable.

**Comment by raarts** [comment]
I see. Thanks for answering. I'll close this issue then.
