### ISSUE TITLE
[16.0] bug account_statement_import_file

### ISSUE THREAD

**Issue by Gelo-fl** [OCA/bank-statement-import#615]
## Module
account_statement_import_file

## Describe the bug
In the readme of the module it says:
"If your statement file contains transactions that have already been imported into Odoo, they will not be created a second time".
But here I show a video where you can see that the same file is imported 2 times. https://www.awesomescreenshot.com/video/19403205?key=05209d72b5317035ac35df8a204a3e8d. Is this behavior correct?

It also says:
"Attach the file to the statement (to facilitate diagnosis in case of problem)",
 but in the statement I don't see it attached anywhere.
![2023-07-25_13-13](https://github.com/OCA/bank-statement-import/assets/126253270/6eebbd6e-ff1d-45ef-8fbd-0697a70513e4)

## To Reproduce
**Affected versions**:
"16.0.1.0.1"
1. Import a statement
2. Import the same statement

**Expected behavior**
If the extract has already been imported, an error message should be displayed to prevent importing the same extract again.
If the file contains more rows and some of them have already been imported, the message should indicate which rows are repeated and not import them.

**Additional context**
There is another open issue to clarify what the multi-account statement file support functionality consists of #614

**Comment by Gelo-fl** [comment]
@alexis-via As the person responsible for the migration of this module in https://github.com/OCA/bank-statement-import/pull/575, could you please check this?

**Comment by willievmobile** [comment]
> 

Hey Gelo,
I just wanted to know if you got the statement import working in 16?
Ive been smashing my head against a wall for about a week now and i just cant get it to work.... i cant get the manual imput to work either as its not even showing a button on the statement page. 
Sorry for the message here but im pretty desperate for any help

**Comment by Gelo-fl** [comment]
Hi @willievmobile For the import of the statemets I am using the module l10n_en_account_statement_import_n43.

**Comment by nagybal** [comment]
@Gelo-fl which accounting module do You use for the dashboard and everything?

**Comment by Gelo-fl** [comment]
l10n_es

**Comment by nagybal** [comment]
@Gelo-fl l10n_es only gives You the config for Spain (chart of accounts, tax templates and etc.) I believe You use the community edition.

I am curious about the accounting dashboard. Is it for example om_account_accountant or base_accounting_kit ?

**Comment by Gelo-fl** [comment]
Hi @nagybal ,

I think this post is not the right place to resolve these doubts. If you post them in the appropriate forum, they may help you resolve your doubts.

**Comment by nagybal** [comment]
@Gelo-fl There is no issue on my side. I just would like to know which add-on do YOU get your dashboard from?

om_account_accountant

or 

base_accounting_kit

?

**Comment by mdfaisalpapa** [comment]
I am using om_account_accountant and unable to import the bank statement in Odoo 16. 

I am able to import in Odoo 15. This is the reason i have not yet upgraded to odoo 16

**Comment by msprancis** [comment]
To enable accounting features in Odoo 16 community go to settings, User Groups, search enable Show Full Accounting Features and add it to your user. I know this is off topic, but I spent a lot of time trying to figure out why Import button is not showing up and appears you don't really need any 3rd party App. Amazing! OCA really need to put this in every bank import statement App readme file.

**Comment by nagybal** [comment]
Are You able to reconcile as well?

**Comment by msprancis** [comment]
Yes. Works great with related a app: "Import Statement Files and Go Direct to Reconciliation" BTW, one of the videos that explain how to enable Full accounting is this: https://www.youtube.com/watch?v=n7YzlQiad0o
