### ISSUE TITLE
[16.0] account_statement_import_sheet_file: keep order of rows in imported file

### ISSUE THREAD

**Issue by cuongnmtm** [OCA/bank-statement-import#669]
When importing bank statements using a sheet file that contains a column with timestamps in date format, the sequence of generated journal items may not match the sequence of lines in the imported file. This happens because the rows are currently being sorted by the timestamp column.

The code that sorts rows by timestamp: https://github.com/OCA/bank-statement-import/blob/9dca998e559af55de972afe82aab627008e96b75/account_statement_import_sheet_file/models/account_statement_import_sheet_parser.py#L68

Example:

STT     No. | TNX Date/ CT/ Doc No | Effective date | Debit | Credit
-- | -- | -- | -- | --
1 | 02/01/2024   / 5254 - 96829 | 02/01/2024 | 6.000 |  
2 | 02/01/2024   / 5136 - 09957 | 02/01/2024 | 2.000 |  
3 | 02/01/2024   / 5136 - 10124 | 02/01/2024 | 2.000 |  
4 | 02/01/2024   / 5136 - 10694 | 02/01/2024 | 7.000 |  
5 | 02/01/2024   / 5136 - 11486 | 02/01/2024 | 15.000 |  
6 | 03/01/2024   / 5009 - 07716 | 03/01/2024 |   | 15.000

generated these journal items

![image](https://github.com/OCA/bank-statement-import/assets/32898439/30280f34-e38b-435a-858c-c3d8f8a902bb)

**Describe the solution you'd like**

A way to avoid sorting rows upon import to preserve their original order. Alternatively, allow for sorting by multiple columns.

**Comment by cuongnmtm** [comment]
I can submit a pull request to improve this, but I'm not sure which direction to take.

Maybe an option on the mapping to skip the sort.

**Comment by rrebollo** [comment]
@cuongnmtm, is this still relevant? Have you found any way to work around this issue?

**Comment by cuongnmtm** [comment]
@rrebollo The workaround is to add a fake time to the date. For example:

2024-12-01 00:00:01
2024-12-01 00:00:02
...

I didn’t try to add a solution because there is an easy workaround.
A proper solution would be to have a new field to specify columns to order the lines.

**Comment by rrebollo** [comment]
> @rrebollo The workaround is to add a fake time to the date. For example:
> 
> 2024-12-01 00:00:01
> 2024-12-01 00:00:02
> ...
> 
> I didn’t try to add a solution because there is an easy workaround.
> A proper solution would be to have a new field to specify columns to order the lines.

Maybe this can be close then.
