### ISSUE TITLE
Bank Statement TXT/CSV/XLSX Import

### ISSUE THREAD

**Issue by fedecarraro** [OCA/bank-statement-import#709]
module: account_statement_import_sheet_file
version: 16.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by fedecarraro** [comment]
Buongiorno a tutti,
dopo aver mappato l'estratto conto in .csv da importare, il sistema non me lo fa fare perchè mi da il seguente errore: "data in not in list" ma la data è presente.

Potete darmi un suggerimento?

Grazie

**Comment by TheMule71** [comment]
Try using column numbers instead of header labels. [Prova ad usare i numeri delle colonne invece che le etichette nella prima riga]

**Comment by rrebollo** [comment]
@pedrobaeza I think U can surely close this: lack of info, no feedback.
