### ISSUE TITLE
[16.0] Error add new statement line

### ISSUE THREAD

**Issue by ljimenezsidoo** [OCA/bank-statement-import#720]
When try to add new line in account.bank.statement after import the bank statement error is displayed

## Module
account

## Describe the bug
![image](https://github.com/user-attachments/assets/b25d194c-1d50-405e-a4d1-c9eda527eb37)

ValueError: Compute method failed to assign account.bank.statement.line(<NewId origin=2>, <NewId origin=1>).running_balance

Compute method should use recodset not newId

## To Reproduce
**Affected versions**: 16.0

1. Go to runboat of this repo bank-statement-import
2. Open one account.bank.statement with lines and try to add new one.

**Expected behavior**
You should create new line without problems

**Comment by rrebollo** [comment]
This doesn't appear to be a bug related to this repository. The traceback doesn't include any lines referencing an addon from this repo. @ljimenezsidoo, is this still relevant here?

**Comment by pedrobaeza** [comment]
This is not of this repo, but anyway it's already fixed, so closing.
