### ISSUE TITLE
odoo 9 impossible to import ofx files

### ISSUE THREAD

**Issue by ericzen** [OCA/bank-statement-import#74]
when importing a ofx file on odoo 9 CE, i have this message

![2016-09-22_23-22-59](https://cloud.githubusercontent.com/assets/16808444/18766675/b0e1034a-811b-11e6-99bd-1c9cb268d5c3.jpg)

Have you a solution please ?

**Comment by pedrobaeza** [comment]
OCA module for importing OFX is not migrated to v9, so maybe you are confused with the enterprise version.

**Comment by alexis-via** [comment]
OCA module for importing OFX file is available for v9 in this PR: https://github.com/OCA/bank-statement-import/pull/70
