### ISSUE TITLE
Gocardless : typing error in the "New link" method call

### ISSUE THREAD

**Issue by arpol-dev** [OCA/bank-statement-import#745]
@pedrobaeza 

## Module
account_statement_import_online_gocardless

## Describe the bug
The new link method - [line link](https://github.com/OCA/bank-statement-import/blob/806d0b6c482a2b4c9ef0048f6b9ca885f6a9f7a3/account_statement_import_online_gocardless/wizards/online_bank_statement_provider_existing.py#L31) - calls a function that is wrong ('institution' is missing a 't')

**Comment by pedrobaeza** [comment]
The method name was incorrect, and it was corrected in 36db32bda23fbe28e4f1e81e1455d7983a9f4d58, but not on the wizard. Can you please do a PR fixing it?

**Comment by arpol-dev** [comment]
@pedrobaeza 
It's running :)
