### ISSUE TITLE
import function for CSV bank statements for odoo8

### ISSUE THREAD

**Issue by Hans-0** [OCA/bank-statement-import#88]
Recently I migrated my database Openerp7 to Odoo8.
In Openerp I had the import function for **ING banking CSV** files.
Is it true that this feature in ODOO 8 has expired?

**Comment by hbrunn** [comment]
as long as nobody pays for migrating this or somebody migrates it for own use, this will stay true.

This is a horrible format anyways, better try if the current CAMT implementation works for your account.

**Comment by Hans-0** [comment]
Ok, I understand. So I don't have tot search for the module.
I will explore the possibilities concerning CAMT.
Thanks!
